version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/SakuraBurst/golang-youtube-downloader

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - nakedret
    - prealloc
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
