package youtube

// CaptionTrack represents a single caption/subtitle track for a video.
type CaptionTrack struct {
	// URL is the URL to download the caption track.
	URL string

	// LanguageCode is the ISO 639-1 language code (e.g., "en", "es", "fr").
	LanguageCode string

	// LanguageName is the human-readable name of the language (e.g., "English", "Spanish").
	LanguageName string

	// IsAutoGenerated indicates if the track was auto-generated by YouTube.
	IsAutoGenerated bool

	// IsTranslatable indicates if the track can be translated to other languages.
	IsTranslatable bool
}

// CaptionManifest contains all available caption tracks for a video.
type CaptionManifest struct {
	// Tracks contains all available caption tracks.
	Tracks []CaptionTrack
}

// HasCaptions returns true if any caption tracks are available.
func (m *CaptionManifest) HasCaptions() bool {
	return len(m.Tracks) > 0
}

// GetTrackByLanguage returns the caption track for the specified language code.
// Returns nil if no track is found for the language.
func (m *CaptionManifest) GetTrackByLanguage(languageCode string) *CaptionTrack {
	for i := range m.Tracks {
		if m.Tracks[i].LanguageCode == languageCode {
			return &m.Tracks[i]
		}
	}
	return nil
}

// GetManualTracks returns only manually created (non-auto-generated) caption tracks.
func (m *CaptionManifest) GetManualTracks() []CaptionTrack {
	var tracks []CaptionTrack
	for _, t := range m.Tracks {
		if !t.IsAutoGenerated {
			tracks = append(tracks, t)
		}
	}
	return tracks
}

// GetAutoGeneratedTracks returns only auto-generated caption tracks.
func (m *CaptionManifest) GetAutoGeneratedTracks() []CaptionTrack {
	var tracks []CaptionTrack
	for _, t := range m.Tracks {
		if t.IsAutoGenerated {
			tracks = append(tracks, t)
		}
	}
	return tracks
}
