package youtube

import (
	"testing"
)

func TestCaptionManifest_HasCaptions(t *testing.T) {
	tests := []struct {
		name     string
		manifest CaptionManifest
		want     bool
	}{
		{
			name:     "empty manifest",
			manifest: CaptionManifest{},
			want:     false,
		},
		{
			name: "manifest with tracks",
			manifest: CaptionManifest{
				Tracks: []CaptionTrack{
					{LanguageCode: "en", LanguageName: "English"},
				},
			},
			want: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.manifest.HasCaptions(); got != tt.want {
				t.Errorf("HasCaptions() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCaptionManifest_GetTrackByLanguage(t *testing.T) {
	manifest := CaptionManifest{
		Tracks: []CaptionTrack{
			{LanguageCode: "en", LanguageName: "English"},
			{LanguageCode: "es", LanguageName: "Spanish"},
			{LanguageCode: "fr", LanguageName: "French"},
		},
	}

	tests := []struct {
		name         string
		languageCode string
		wantNil      bool
		wantName     string
	}{
		{
			name:         "find English",
			languageCode: "en",
			wantNil:      false,
			wantName:     "English",
		},
		{
			name:         "find Spanish",
			languageCode: "es",
			wantNil:      false,
			wantName:     "Spanish",
		},
		{
			name:         "language not found",
			languageCode: "de",
			wantNil:      true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			track := manifest.GetTrackByLanguage(tt.languageCode)
			if tt.wantNil {
				if track != nil {
					t.Errorf("GetTrackByLanguage(%q) = %v, want nil", tt.languageCode, track)
				}
			} else {
				if track == nil {
					t.Fatalf("GetTrackByLanguage(%q) = nil, want non-nil", tt.languageCode)
				}
				if track.LanguageName != tt.wantName {
					t.Errorf("GetTrackByLanguage(%q).LanguageName = %q, want %q", tt.languageCode, track.LanguageName, tt.wantName)
				}
			}
		})
	}
}

func TestCaptionManifest_GetManualTracks(t *testing.T) {
	manifest := CaptionManifest{
		Tracks: []CaptionTrack{
			{LanguageCode: "en", LanguageName: "English", IsAutoGenerated: false},
			{LanguageCode: "en-auto", LanguageName: "English (auto)", IsAutoGenerated: true},
			{LanguageCode: "es", LanguageName: "Spanish", IsAutoGenerated: false},
		},
	}

	tracks := manifest.GetManualTracks()
	if len(tracks) != 2 {
		t.Errorf("GetManualTracks() returned %d tracks, want 2", len(tracks))
	}
	for _, track := range tracks {
		if track.IsAutoGenerated {
			t.Errorf("GetManualTracks() returned auto-generated track: %v", track)
		}
	}
}

func TestCaptionManifest_GetAutoGeneratedTracks(t *testing.T) {
	manifest := CaptionManifest{
		Tracks: []CaptionTrack{
			{LanguageCode: "en", LanguageName: "English", IsAutoGenerated: false},
			{LanguageCode: "en-auto", LanguageName: "English (auto)", IsAutoGenerated: true},
			{LanguageCode: "fr-auto", LanguageName: "French (auto)", IsAutoGenerated: true},
		},
	}

	tracks := manifest.GetAutoGeneratedTracks()
	if len(tracks) != 2 {
		t.Errorf("GetAutoGeneratedTracks() returned %d tracks, want 2", len(tracks))
	}
	for _, track := range tracks {
		if !track.IsAutoGenerated {
			t.Errorf("GetAutoGeneratedTracks() returned non-auto-generated track: %v", track)
		}
	}
}

func TestPlayerResponse_ExtractCaptionManifest(t *testing.T) {
	// Test with captions present
	html := `<!DOCTYPE html>
<script>var ytInitialPlayerResponse = {
	"videoDetails":{"videoId":"test123","title":"Test Video","lengthSeconds":"120"},
	"playabilityStatus":{"status":"OK"},
	"captions":{
		"playerCaptionsTracklistRenderer":{
			"captionTracks":[
				{
					"baseUrl":"https://www.youtube.com/api/timedtext?v=test123&lang=en",
					"vssId":".en",
					"languageCode":"en",
					"name":{"simpleText":"English"},
					"isTranslatable":true
				},
				{
					"baseUrl":"https://www.youtube.com/api/timedtext?v=test123&lang=es",
					"vssId":".es",
					"languageCode":"es",
					"name":{"simpleText":"Spanish"},
					"isTranslatable":true
				}
			]
		}
	}
};</script>`

	page := &WatchPage{VideoID: "test123", HTML: html}
	pr, err := page.ExtractPlayerResponse()
	if err != nil {
		t.Fatalf("ExtractPlayerResponse failed: %v", err)
	}

	manifest := pr.ExtractCaptionManifest()
	if !manifest.HasCaptions() {
		t.Error("Expected manifest to have captions")
	}
	if len(manifest.Tracks) != 2 {
		t.Errorf("Expected 2 tracks, got %d", len(manifest.Tracks))
	}

	enTrack := manifest.GetTrackByLanguage("en")
	if enTrack == nil {
		t.Fatal("Expected to find English track")
	}
	if enTrack.LanguageName != "English" {
		t.Errorf("Expected language name 'English', got %q", enTrack.LanguageName)
	}
	if enTrack.URL == "" {
		t.Error("Expected URL to be non-empty")
	}
}

func TestPlayerResponse_ExtractCaptionManifest_AutoGenerated(t *testing.T) {
	html := `<!DOCTYPE html>
<script>var ytInitialPlayerResponse = {
	"videoDetails":{"videoId":"test123","title":"Test Video","lengthSeconds":"120"},
	"playabilityStatus":{"status":"OK"},
	"captions":{
		"playerCaptionsTracklistRenderer":{
			"captionTracks":[
				{
					"baseUrl":"https://www.youtube.com/api/timedtext?v=test123&lang=en&kind=asr",
					"vssId":"a.en",
					"languageCode":"en",
					"kind":"asr",
					"name":{"simpleText":"English (auto-generated)"},
					"isTranslatable":true
				}
			]
		}
	}
};</script>`

	page := &WatchPage{VideoID: "test123", HTML: html}
	pr, err := page.ExtractPlayerResponse()
	if err != nil {
		t.Fatalf("ExtractPlayerResponse failed: %v", err)
	}

	manifest := pr.ExtractCaptionManifest()
	if !manifest.HasCaptions() {
		t.Error("Expected manifest to have captions")
	}

	autoTracks := manifest.GetAutoGeneratedTracks()
	if len(autoTracks) != 1 {
		t.Errorf("Expected 1 auto-generated track, got %d", len(autoTracks))
	}
	if !autoTracks[0].IsAutoGenerated {
		t.Error("Expected track to be marked as auto-generated")
	}
}

func TestPlayerResponse_ExtractCaptionManifest_NoCaptions(t *testing.T) {
	html := `<!DOCTYPE html>
<script>var ytInitialPlayerResponse = {
	"videoDetails":{"videoId":"test123","title":"Test Video","lengthSeconds":"120"},
	"playabilityStatus":{"status":"OK"}
};</script>`

	page := &WatchPage{VideoID: "test123", HTML: html}
	pr, err := page.ExtractPlayerResponse()
	if err != nil {
		t.Fatalf("ExtractPlayerResponse failed: %v", err)
	}

	manifest := pr.ExtractCaptionManifest()
	if manifest.HasCaptions() {
		t.Error("Expected manifest to have no captions")
	}
}
